-- ============================================================================
-- Campus Management System - Sample / Demo Data
-- Optional: loads one account per role (matching the README's "Demo
-- credentials" section) plus a few sample courses, so the app has something
-- to look at immediately after the schema is created. Not required for the
-- schema itself - see db/migrations/001_schema.sql for that.
--
-- Password hashes below are real BCrypt hashes (cost factor 12) generated by
-- com.campus.util.PasswordUtil for the plaintext passwords documented in the
-- README. These are demo-only credentials for local evaluation, never real
-- production accounts.
-- ============================================================================

USE campus_management;

INSERT INTO users (username, password_hash, role, email, full_name, is_active) VALUES
    ('admin',    '$2a$12$NVyBLg0yEWASrUNyjSGHdeJRVvBpBplAc4rJmq3ZuBSB90ZhYmqrC', 'ADMIN',   'admin@campus.edu',   'System Administrator', 1),
    ('faculty1', '$2a$12$IN5DgC9PUDn0/pw2yvwgoeuHYSS/kD5qVfdNEbDCdAwr5Ia7l9RBu', 'FACULTY', 'emartinez@campus.edu', 'Dr. Elena Martinez', 1),
    ('student1', '$2a$12$0bT23tdomgZ2LHVgZ2Bm6.USJnr9Fu7RXdqt6IcQeXlhcCDX10C5C', 'STUDENT', 'mjohnson@campus.edu', 'Marcus Johnson', 1);

INSERT INTO faculty (user_id, department, title, office_location)
SELECT id, 'Computer Science', 'Associate Professor', 'Turing Hall 214' FROM users WHERE username = 'faculty1';

INSERT INTO students (user_id, student_number, enrollment_year, major, date_of_birth)
SELECT id, 'S00123456', 2024, 'Computer Science', '2004-03-15' FROM users WHERE username = 'student1';

INSERT INTO courses (code, title, credits, faculty_id, capacity, semester)
SELECT 'CS101', 'Introduction to Programming', 3, u.id, 30, 'FALL2024'
FROM users u WHERE u.username = 'faculty1';

INSERT INTO courses (code, title, credits, faculty_id, capacity, semester)
SELECT 'CS201', 'Data Structures', 3, u.id, 25, 'FALL2024'
FROM users u WHERE u.username = 'faculty1';

INSERT INTO courses (code, title, credits, faculty_id, capacity, semester)
VALUES ('MATH150', 'Calculus I', 4, NULL, 40, 'FALL2024');
